# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from waterlinked_a50_ros_driver/DVLBeam.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DVLBeam(genpy.Message):
  _md5sum = "750bcc69eae0dec5dc80e15e3ced915b"
  _type = "waterlinked_a50_ros_driver/DVLBeam"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#Transducer ID
int64 id
#Velocity reported by transducer
float64 velocity
#Distance value
float64 distance
#RSSI
float64 rssi
#NSD
float64 nsd
#Report if beam is locked on and providing reliable data
bool valid
"""
  __slots__ = ['id','velocity','distance','rssi','nsd','valid']
  _slot_types = ['int64','float64','float64','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,velocity,distance,rssi,nsd,valid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DVLBeam, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.velocity is None:
        self.velocity = 0.
      if self.distance is None:
        self.distance = 0.
      if self.rssi is None:
        self.rssi = 0.
      if self.nsd is None:
        self.nsd = 0.
      if self.valid is None:
        self.valid = False
    else:
      self.id = 0
      self.velocity = 0.
      self.distance = 0.
      self.rssi = 0.
      self.nsd = 0.
      self.valid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q4dB().pack(_x.id, _x.velocity, _x.distance, _x.rssi, _x.nsd, _x.valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.id, _x.velocity, _x.distance, _x.rssi, _x.nsd, _x.valid,) = _get_struct_q4dB().unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q4dB().pack(_x.id, _x.velocity, _x.distance, _x.rssi, _x.nsd, _x.valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 41
      (_x.id, _x.velocity, _x.distance, _x.rssi, _x.nsd, _x.valid,) = _get_struct_q4dB().unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q4dB = None
def _get_struct_q4dB():
    global _struct_q4dB
    if _struct_q4dB is None:
        _struct_q4dB = struct.Struct("<q4dB")
    return _struct_q4dB
